/**
 * Root layout for the entire App Router tree: global styles, theme + session providers, toast host,
 * achievement listener, and service worker registration (production only — dev unregisters SWs
 * to protect Fast Refresh).
 */
import type { Metadata } from "next";
import "./globals.css";
import { getSiteUrl } from "@/lib/seo";
import { Toaster } from "@/components/ui/sonner";
import { AchievementListener } from "@/components/achievement-listener";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/components/theme-provider";
import { Instrument_Serif, JetBrains_Mono, Noto_Sans, Plus_Jakarta_Sans } from "next/font/google";
import localFont from "next/font/local";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages, getTranslations } from "next-intl/server";

const instrumentSerif = Instrument_Serif({
  weight: ["400"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-instrument-serif",
  display: "swap",
});

const jetBrainsMono = JetBrains_Mono({
  weight: ["400", "500"],
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  display: "swap",
});

// Geometric sans used by the redesigned (Aurora) landing page. Scoped via CSS var;
// existing pages keep their system-ui body font.
const plusJakarta = Plus_Jakarta_Sans({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-jakarta",
  display: "swap",
});

// Noto Sans — loaded for its comprehensive Unicode/IPA coverage.
// Acts as a harmonious fallback for any character not in Plus Jakarta Sans
// or JetBrains Mono, preventing the OS from substituting a mismatched
// system font that renders IPA glyphs at incorrect weight or size.
const notoSans = Noto_Sans({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-noto",
  display: "swap",
});

// Gilroy — locally-hosted display face used for the Cyrillic locales (Russian
// and Ukrainian; includes Cyrillic). Applied via the `html[lang="free-ru"]` and
// `html[lang="uk"]` selectors in globals.css; English keeps Jakarta untouched.
// Ships the weights the UI actually uses (light → extrabold); Noto Sans remains
// the fallback for any missing glyph.
const gilroy = localFont({
  src: [
    { path: "./fonts/Gilroy-Light.ttf", weight: "300", style: "normal" },
    { path: "./fonts/Gilroy-Regular.ttf", weight: "400", style: "normal" },
    { path: "./fonts/Gilroy-Medium.ttf", weight: "500", style: "normal" },
    { path: "./fonts/Gilroy-Semibold.ttf", weight: "600", style: "normal" },
    { path: "./fonts/Gilroy-Bold.ttf", weight: "700", style: "normal" },
    { path: "./fonts/Gilroy-Extrabold.ttf", weight: "800", style: "normal" },
  ],
  variable: "--font-gilroy",
  display: "swap",
});


const siteUrl = getSiteUrl();

export async function generateMetadata(): Promise<Metadata> {
  const t = await getTranslations("seo.root")
  return {
  metadataBase: new URL(siteUrl),
  title: {
    default: t("title"),
    template: "%s | LingoCon",
  },
  description: t("description"),
  keywords: [
    // Brand keywords — helps Google associate these terms with lingocon.com
    "LingoCon", "lingocon.com", "lingocon conlang",
    // Primary target keywords
    "conlang", "conlang tools", "conlang maker", "conlang builder", "conlang creator", "conlang platform", "conlang software",
    // Constructed language variants
    "constructed language", "constructed language maker", "constructed language builder", "constructed language tools", "invented language", "artificial language", "fictional language",
    // Action-oriented
    "create a conlang", "how to create a conlang", "language creation", "language design", "language invention", "make a language online",
    // Feature keywords
    "lexicon builder", "grammar documentation", "phonology builder", "morphology tables", "IPA dictionary", "conlang dictionary", "grammar wiki", "language family tree", "interlinear glossing",
    // Community & sharing
    "conlang community", "share conlang", "conlang documentation", "public conlang",
    // Adjacent use cases
    "worldbuilding language", "worldbuilding tools", "fictional language creator", "language inventor", "linguistics documentation", "tolkien style language", "elvish language creator",
    // Free / online
    "free conlang tool", "online conlang maker", "best conlang tool 2025",
  ],
  authors: [{ name: "LingoCon", url: siteUrl }, { name: "Alexander Chepkov", url: "https://github.com/alexcircuits" }],
  creator: "Alexander Chepkov",
  publisher: "LingoCon",
  category: "Language Tools",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteUrl,
    siteName: "LingoCon",
    title: t("ogTitle"),
    description: t("ogDescription"),
    // Open Graph image is generated by app/opengraph-image.tsx (file convention).
  },
  twitter: {
    card: "summary_large_image",
    title: t("twitterTitle"),
    description: t("twitterDescription"),
    // Twitter image is generated by app/twitter-image.tsx (file convention).
  },
  alternates: {
    canonical: siteUrl,
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "LingoCon",
  },
  other: {
    "google-site-verification": process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION || "",
  },
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        <link rel="apple-touch-icon" href="/icons/apple-touch-icon.png" />
        <meta name="theme-color" content="#7c5cff" />
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var p=localStorage.getItem('palette');if(p==='classic'){document.documentElement.setAttribute('data-palette','classic');}}catch(e){}})();`,
          }}
        />
      </head>
      <body className={`${instrumentSerif.variable} ${jetBrainsMono.variable} ${plusJakarta.variable} ${notoSans.variable} ${gilroy.variable} min-h-screen antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>
            <NextIntlClientProvider messages={messages}>
              {children}
              <AchievementListener />
              <Toaster
                position="bottom-right"
                toastOptions={{
                  className: "border-border/50 bg-card shadow-soft",
                }}
              />
            </NextIntlClientProvider>
          </SessionProvider>
        </ThemeProvider>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if ('serviceWorker' in navigator) {
                if ('${process.env.NODE_ENV}' === 'production') {
                  window.addEventListener('load', () => {
                    navigator.serviceWorker.register('/sw.js').catch(() => {});
                  });
                } else {
                  // In development mode, unregister any existing service workers
                  // to prevent them from aggressively caching Webpack HMR chunks
                  // and causing "originalFactory is undefined" errors.
                  navigator.serviceWorker.getRegistrations().then(function(registrations) {
                    for(let registration of registrations) {
                      registration.unregister();
                    }
                  });
                }
              }
            `,
          }}
        />
      </body>
    </html>
  );
}

